
apiVersion: v1
kind: Service
metadata:
  name: exchange-rate-service
spec:
  selector:
    app: exchange-rate-service
  ports:
    - protocol: TCP
      port: 3334
      targetPort: 3334
  type: NodePort
